# Generated by Django 5.2.5 on 2025-12-23 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_genre_post_likes_post_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categories',
            new_name='genres',
        ),
    ]
